"""Correctness suite: assert the current code reproduces upstream's numerics.

The fixtures in `tests/fixtures/golden.pt` were generated by running the
*original upstream implementation* (see `tests/generate_fixtures.py` for the
exact procedure and for what is deliberately out of scope). This module replays
the recorded inputs through the current code and compares against the recorded
outputs.

Each case checks two things in order:

1. **Parameter checksum.** Weights are rebuilt from a fixed seed rather than
   stored, so if module construction changes -- a new layer, a reordered
   `nn.Module` attribute, a different init -- the weights differ and every
   output would differ too. Checking the checksum first turns that into a clear
   "initialisation changed" failure instead of a confusing numerical one.
2. **Outputs**, via `torch.testing.assert_close` at a tight but non-bitwise
   tolerance. Bitwise equality is not asserted because einsum/bmm may pick
   different reduction orders depending on tensor contiguity.

Run:
    python -m tests.test_correctness
    pytest tests/test_correctness.py
"""

import importlib
from pathlib import Path

import torch

from tests.generate_fixtures import build_cases

FIXTURE_PATH = Path(__file__).parent / "fixtures" / "golden.pt"
PACKAGE = "msa_pairformer"

# Tight enough to catch a real numerical change, loose enough to tolerate
# reduction-order differences between contiguity states.
RTOL, ATOL = 1e-5, 1e-6


def load_fixture():
    if not FIXTURE_PATH.exists():
        raise FileNotFoundError(
            f"{FIXTURE_PATH} is missing. Regenerate it from the upstream tree; "
            "see the docstring in tests/generate_fixtures.py."
        )
    return torch.load(FIXTURE_PATH, weights_only=False)


def _check_case(name, case_fn, expected):
    module, _inputs, actual = case_fn()

    from tests.generate_fixtures import param_checksum
    got_checksum = param_checksum(module)
    if got_checksum != expected["param_checksum"]:
        raise AssertionError(
            f"{name}: module initialisation changed -- parameter checksum "
            f"{got_checksum[:16]} != recorded {expected['param_checksum'][:16]}. "
            "Outputs cannot be meaningfully compared; if this change is "
            "intentional, regenerate the fixtures."
        )

    assert set(actual) == set(expected["outputs"]), (
        f"{name}: output keys changed: {sorted(actual)} != "
        f"{sorted(expected['outputs'])}"
    )

    for key, want in expected["outputs"].items():
        have = actual[key]
        if want is None:
            assert have is None, f"{name}.{key}: expected None, got a tensor"
            continue
        assert have.shape == want.shape, (
            f"{name}.{key}: shape {tuple(have.shape)} != {tuple(want.shape)}"
        )
        torch.testing.assert_close(
            have, want, rtol=RTOL, atol=ATOL,
            msg=lambda m, _n=name, _k=key: f"{_n}.{_k} diverged from upstream:\n{m}",
        )


def build_checks():
    """Pair each fixture case with the callable that reproduces it."""
    fixture = load_fixture()
    cases = dict(build_cases(PACKAGE))
    recorded = fixture["cases"]

    missing = set(recorded) - set(cases)
    assert not missing, f"fixture has cases with no generator: {sorted(missing)}"

    return fixture, [
        (name, cases[name], recorded[name]) for name in recorded
    ]


def test_all_cases_match_upstream():
    _fixture, checks = build_checks()
    for name, case_fn, expected in checks:
        _check_case(name, case_fn, expected)


def test_fixture_covers_the_core_stack():
    """Guard against the suite silently shrinking to a trivial subset."""
    fixture = load_fixture()
    required = {
        "core.Transition",
        "pairwise_operations.MSAPairWeightedAveraging",
        "pairwise_operations.TriangleMultiplication[outgoing]",
        "pairwise_operations.TriangleMultiplication[incoming]",
        "outer_product.OuterProduct[presoftmax_differential]",
        "model.MSAPairformer.forward",
    }
    missing = required - set(fixture["cases"])
    assert not missing, f"fixture no longer covers: {sorted(missing)}"


def test_fixture_came_from_upstream():
    """The goldens are only meaningful if they were recorded from the original
    implementation, not regenerated from the code under test."""
    meta = load_fixture()["metadata"]
    assert meta["source_package"] == "MSA_Pairformer", (
        f"fixtures were generated from {meta['source_package']!r}, not the "
        "upstream package. They pin current behaviour rather than upstream's."
    )


if __name__ == "__main__":
    fixture, checks = build_checks()
    meta = fixture["metadata"]
    print(f"fixture: {len(checks)} cases from {meta['source_package']} "
          f"(torch {meta['torch_version']}, {meta['triangle_path']} triangle path)")
    importlib.import_module(PACKAGE)

    failures = 0
    for name, case_fn, expected in checks:
        try:
            _check_case(name, case_fn, expected)
        except AssertionError as exc:
            print(f"  FAIL {name}\n        {str(exc).splitlines()[0]}")
            failures += 1
        else:
            print(f"  ok   {name}")

    for extra in (test_fixture_covers_the_core_stack, test_fixture_came_from_upstream):
        try:
            extra()
        except AssertionError as exc:
            print(f"  FAIL {extra.__name__}: {exc}")
            failures += 1
        else:
            print(f"  ok   {extra.__name__}")

    print("all cases match upstream" if not failures else f"{failures} case(s) FAILED")
    raise SystemExit(1 if failures else 0)
